### ISSUE TITLE
Don`t create dependency-check-report.xml. Gitlab CI. 

### ISSUE THREAD

**Issue by patsevanton** [dependency-check/DependencyCheck#2412]
Repository:
https://gitlab.com/anton_patsev/findbugs-example3

Gitlab-ci.yml
```
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=~/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dmaven.test.skip=true "
  DEPENDENCYCHECK_OPTS: "-Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html"
  SONAR_HOST_URL: "http://172.26.9.223:9000"
  LOGIN: "admin"
  PASSWORD: "admin"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS $DEPENDENCYCHECK_OPTS clean verify org.owasp:dependency-check-maven:check -X
    - find . -name dependency-check-report*
    - mvn $MAVEN_CLI_OPTS $DEPENDENCYCHECK_OPTS verify org.owasp:dependency-check-maven:aggregate -X
    - find . -name dependency-check-report*
```

But file have

![image](https://user-images.githubusercontent.com/10828883/71908229-cef1d780-3197-11ea-923c-7ee8c195326f.png)

Full Log
https://gist.github.com/patsevanton/68dbd0e1e2434e4648b1df6359fd364e
