### ISSUE TITLE
dependency-check.sh not found vulnerability in pom.xml

### ISSUE THREAD

**Issue by patsevanton** [dependency-check/DependencyCheck#2436]
Hello.
I am download dependency-check-5.3.0-release.zip to gitlab runner.
```
/var/lib/dependency-check
/var/lib/dependency-check/bin
/var/lib/dependency-check/bin/dependency-check.bat
/var/lib/dependency-check/bin/dependency-check.sh
/var/lib/dependency-check/lib
/var/lib/dependency-check/lib/annotations-18.0.0.jar
...
```

Try to scan https://github.com/patsevanton/dependency-check-example

Created .gitlab-ci.yml:
```
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=~/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DEPENDENCY_OPTS: "--data ./tmp --failOnCVSS=1"

before_script:
  - export PATH="/var/lib/dependency-check/bin:$PATH"

verify:
  stage: test
  script:
    - set +e
    - dependency-check.sh --project "$CI_PROJECT_NAME" --scan "./" $DEPENDENCY_OPTS || EXIT_CODE=$?
    - ls
    - pwd
    - export PATH_WITHOUT_HOME=$(pwd | sed -e "s/\/home\/gitlab-runner\/builds//g")
    - echo "************************* URL Dependency-check-report.html *************************"
    - echo "http://$HOSTNAME:9999$PATH_WITHOUT_HOME/dependency-check-report.html"
    - set -e
    - exit ${EXIT_CODE}
  tags:
    - shell
```

Full log:
https://gist.github.com/patsevanton/a5748b77726f26ce85cf724f644efc64

Pom.xml have vulnerability.
But dependency-check.sh not found vulnerability

![Снимок экрана от 2020-01-19 16-06-32](https://user-images.githubusercontent.com/10828883/72679047-ae017e80-3ad5-11ea-935b-998adfc5d073.png)

![Снимок экрана от 2020-01-19 16-08-13](https://user-images.githubusercontent.com/10828883/72679084-fd47af00-3ad5-11ea-8f04-471241b50ea2.png)

![Снимок экрана от 2020-01-19 16-09-26](https://user-images.githubusercontent.com/10828883/72679097-14869c80-3ad6-11ea-8b36-e95d01d12505.png)

**Comment by patsevanton** [comment]
If use 
```
mvn $MAVEN_CLI_OPTS -DretireJsAnalyzerEnabled=false test org.owasp:dependency-check-maven:check 
```
then will found vulnerability

```
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DEPENDENCY_OPTS: "-DfailBuildOnCVSS=7 -DcveUrlModified=http://localhost:12345/nvdcve-1.1-modified.json.gz -DcveUrlBase=http://localhost:12345/nvdcve-1.1-%d.json.gz"

cache:
  paths:
    - .m2/repository

verify:
  stage: test
  script:
    - set +e
    - mvn $MAVEN_CLI_OPTS -DretireJsAnalyzerEnabled=false test org.owasp:dependency-check-maven:check $DEPENDENCY_OPTS || EXIT_CODE=$?
    - export PATH_WITHOUT_HOME=$(pwd | sed -e "s/\/home\/gitlab-runner\/builds//g")
    - echo "************************* URL Dependency-check-report.html *************************"
    - echo "http://$HOSTNAME:9999$PATH_WITHOUT_HOME/target/dependency-check-report.html"
    - set -e
    - exit ${EXIT_CODE}
  tags:
    - shell
```

![Снимок экрана от 2020-01-19 16-18-53](https://user-images.githubusercontent.com/10828883/72679224-667bf200-3ad7-11ea-8e4d-3fb00c0a12d2.png)
