### ISSUE TITLE
Format Json report not compatible with gitlab-ci security dashboard, vulnerability report

### ISSUE THREAD

**Issue by iamnhl96** [dependency-check/DependencyCheck#3629]
I read format json report of dependency check in gitlab: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#reports-json-format

But i run dependency check 6.0.0 with command:
```/opt/devsecops/dependency-check/bin/dependency-check.sh --proxyserver XXX --proxyport XXX --suppression XXX -s $CI_PROJECT_DIR -f ALL --project $CI_PROJECT_NAME --enableExperimental -o $CI_PROJECT_DIR --go $GOLANG_PATH```

and export report to gitlab:
```
artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/dependency-check-report.html
      - $CI_PROJECT_DIR/dependency-check-report.json
    reports:
      dependency_scanning: $CI_PROJECT_DIR/dependency-check-report.json
```
I read file report htmll and json and have bug critical. But not show in security dashboard, vulnerability report.

I try with template: https://gitlab.com/gitlab-ci-utils/gitlab-ci-templates/-/blob/master/jobs/OWASP-Dependency-Check.gitlab-ci.yml
but not working, metrics.txt is zero.

I see this error bc conflict format json report of dependency check owasp and Reports JSON format dependency of gitlab.
