### ISSUE TITLE
Affected file reported in an excluded path.

### ISSUE THREAD

**Issue by zioalex** [dependency-check/DependencyCheck#4030]
**Describe the bug**
I am running the [Azure DevOps task ](https://marketplace.visualstudio.com/items?itemName=dependency-check.dependencycheck) to run the dependency check.
It reports affected file in an excluded dir.

**Version of dependency-check used**
dependency-check version: 6.5.3 cli version

**Log file**
https://gist.github.com/zioalex/5182ccd710f971b189a1f4478de769fc

**To Reproduce**
Create an ADO pipeline with:
1.
```
 - task: dependency-check-build-task@6
        continueOnError: true 
        displayName: 'Dependency Check'
        inputs:
          projectName: 'TestProject'
          scanPath: '/'
          excludePath: '/tmp/'
          format: 'XML, HTML, JSON, JUNIT'
          failOnCVSS: '7'
          reportsDirectory: '$(System.DefaultWorkingDirectory)/Reports'
          reportFilename: 'dependencyCheckReport.html'
          additionalArguments: '--proxyserver "1.1.1.1" --proxyport "8080"  --disableBundleAudit --disableYarnAudit --dotnet /agent/_work/_tool/dotnet -d /agent/dependency_check_data --disableAssembly --disableNuspec'
```
2. Run the pipeline
3. Check the logs

**Expected behavior**
I expect to do not see any report for files in /tmp but in reality I see them:
```
Microsoft.AspNetCore:2.2.0

File Path: /tmp/dctempf30910d8-b4d9-49dc-92b1-197a7fbd1fb7/check17101887781542396315tmp/102/content/ReactRedux-CSharp/Company.WebApplication1.csproj
```

As also in the output.
**Additional context**
