### ISSUE TITLE
Could not execute .NET AssemblyAnalyzer - since upgrade from 6.5.3 to 7.0.0

### ISSUE THREAD

**Issue by meArchive13** [dependency-check/DependencyCheck#4185]
Since upgrading form version 6.5.3 to 7.0.0 I get the following error

[ERROR] Could not execute .NET AssemblyAnalyzer
Dependency Check completed with exit code 4294967282.
Dependency Check reports:
[ 'D:\\a\\1\\TestResults\\dependency-check\\TEST-NUGET-DEPENDENCIES.xml' ]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 4294967282)."

I use the AzureDevOps Task:
```
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'Nuget Check'
      scanPath: '$(Agent.BuildDirectory)/s/Packages/**/*.dll'
      format: 'JUNIT'
      suppressionPath: '$(System.DefaultWorkingDirectory)/nuget-suppressions.xml'
      reportFilename: 'TEST-NUGET-DEPENDENCIES.xml'
```

When I put the additional parameter to the task definition  under inputs:
`dependencyCheckVersion: '6.5.3'`
everything works fine.

Can anyone help me with this or fix this?
Thank you.
