### ISSUE TITLE
JAVA_HOME is not defined correctly

### ISSUE THREAD

**Issue by john047** [dependency-check/DependencyCheck#4615]
Hello,

I try to run following job in gitlab-ci:

```
owasp:
  stage: dependency-check
  image: docker:19.03.12
  before_script:
    - export DC_DIRECTORY=$HOME/OWASP-Dependency-Check
    - export DATA_DIRECTORY="$DC_DIRECTORY/data"
  script:
    - docker run --name ${CI_JOB_ID} -v ${DATA_DIRECTORY}:/usr/share/dependency-check/data -v ${CI_PROJECT_DIR}:/opt ${DOCKER_REGISTRY}/owasp:7.1.1 /usr/share/dependency-check/data/bin/dependency-check.sh --scan /opt --project "$CI_PROJECT_NAME" --out owasp
    - docker cp ${CI_JOB_ID}:/opt/owasp ${CI_PROJECT_DIR}/owasp
  artifacts:
    paths:
      - owasp
    expire_in: 1h
```

and get next error:
```
Error: JAVA_HOME is not defined correctly.
We cannot execute /opt/jdk/bin/java
ERROR: Job failed: exit code 1
```

How can I start owasp tool using docker run?

**Comment by john047** [comment]
I managed to run the owasp tool by building an image with docker and java (docker190312_openjdk14).
```
owasp:
  stage: dependency-check
  image: ${DOCKER_REGISTRY}/docker190312_openjdk14
  before_script:
    - export DC_PROJECT=${CI_PROJECT_NAME}
    - docker login -u ${DOCKER_REGISTRY_USERNAME} -p ${DOCKER_REGISTRY_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - docker run --name ${CI_JOB_ID} -v ${CI_PROJECT_DIR}:/src:z ${DOCKER_REGISTRY}/owasp:7.1.1 --scan /src --project "$DC_PROJECT" --out /report/owasp
    - docker cp ${CI_JOB_ID}:/report/owasp ${CI_PROJECT_DIR}/owasp
  artifacts:
    paths:
      - owasp
    expire_in: 1h
```
However, after the report is generated, it is empty, that is, I download the report, open the file and follow the link Display: Showing Vulnerable Dependencies (click to show all) nothing - empty.
Why?
Please help!

**Comment by john047** [comment]
Do I understand correctly that the directory with the project ($CI_PROJECT_DIR variable) is not mounted into the container with the owasp tool and the --scan key scans an empty directory?
How to scan a project?

**Comment by aikebah** [comment]
it's more likely that your source directory contains just that: the project's sources. dependency-check CLI is not meant to scan plain project sources, it will miss out all the dependencies. You should typically use a project build tool's integration (Ant, Maven, Gradle, SBT plugins) rather than the CLI. The CLI is geared towards scanning a set of binary libraries assuming those are your project's dependencies. It will not analyze project build configuration dependency definitions.

**Comment by john047** [comment]
The directory with the project contains files (.cs, .json), also at the next job:
```
owasp:
  stage: dependency-check
  image:
    name: ${DOCKER_REGISTRY}/owasp:latest
    entrypoint: [ "" ]
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh --project ${CI_PROJECT_NAME} --scan ${CI_PROJECT_DIR} --out owasp
  artifacts:
    paths:
      - owasp
    expire_in: 1 weeks
```
the report is generated.
But when I run the owasp utility using docker (docker-in-docker) as described [above](https://github.com/jeremylong/DependencyCheck/issues/4615#issuecomment-1160860036), the report is empty.
