### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by AntonOellerer** [dependency-check/DependencyCheck#5398]
Hey,

**Describe the bug**
I am unsuccessfully trying to exclude a directory from a github action analysis:

The directory layout of the project is so that the top level directory containes `src/` and `examples/`, with `examples` further containing a directory in which a `package-lock.json` lies.
You can take a look at the layout [here](https://github.com/DDS-GmbH/s3-metadata-tagger-lib/)

**Version of dependency-check used**
[dependency-check/Dependency-Check_Action@main](https://github.com/dependency-check/Dependency-Check_Action)
I filed an issue [there](https://github.com/dependency-check/Dependency-Check_Action/issues/20), but was redirected here

**Log file**
[log file](https://gist.github.com/AntonOellerer/d1b98c8ffe21be35c5e02e15ef5cc8dc)

**To Reproduce**
I set up the action as follows:
```yml
  dependency-check:
    name: run owasp dependency check
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          cache-dependency-path: "pyproject.toml"
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Run owasp dependency check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 's3-metadata-tagger'
          path: '.'
          format: 'HTML'    
          args: >
            --failOnCVSS 6
            --exclude '**/examples/*'
```

**Expected behavior**
The examples directory gets excluded from the analysis, no vulnerabilities are reported.

**Additional context**
The analysis fails due to vulnerable dependencies in the examples directory

**Comment by jeremylong** [comment]
See issue https://github.com/jeremylong/DependencyCheck/issues/4995 - `myproject.toml` is still not supported. I'll look at resolving that shortly. However, to answer your immediate question you should use:

```yaml
          args: >
            --failOnCVSS 6
            --exclude '**/examples/**'
            --enableExperimental
```

The exclude uses ant style globbing and we are matching against files not directories - so two asterisks are required.

**Comment by AntonOellerer** [comment]
Hey, thank you for the quick response!
Unfortunately, this did not work either, I attached the log of the analysis
[6_Run owasp dependency check.txt](https://github.com/jeremylong/DependencyCheck/files/10536117/6_Run.owasp.dependency.check.txt)

**Comment by jeremylong** [comment]
Can you add:

```yaml
          args: >
            --failOnCVSS 6
            --exclude '**/examples/**'
            --enableExperimental
            --log odc.log
      - name: Archive ODC log
        id: archive-logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: odc-logs
          retention-days: 7
          path: odc.log
```

Then download and provide the log?
