### ISSUE TITLE
Azure Pipelines Task: when using long additionalArguments, arguments that get pushed down a line are ignored

### ISSUE THREAD

**Issue by thisjustin816** [dependency-check/DependencyCheck#6032]
**Describe the bug**
I was trying to add a `--retireJsUrl` as a workaround for #6028, and discovered that when I added it as the last argument, it was ignored. The only indication of why was that in the console it showed the argument on a new line.

**Version of dependency-check used**
8.4.2 with azure pipelines task

**Log file**
N/A

**To Reproduce**
Use yaml like the following
```yaml
          - task: dependency-check-build-task@6
            displayName: OWASP Dependency Check
            inputs:
              projectName: '${{ parameters.release }}'
              scanPath: '$(Pipeline.Workspace)/${{ parameters.release }}Artifact/${{ coalesce(parameters.artifactName, parameters.product, ''drop'') }}'
              format: 'HTML, JUNIT'
              failOnCVSS: '$(failOnCVSS)'
              suppressionPath: '$(Pipeline.Workspace)\owasp-suppression.xml'
              enableExperimental: ${{ parameters.enableExperimental }}
              additionalArguments: >
                --ossIndexUsername $(ossIndexUsername)
                --ossIndexPassword $(ossIndexPassword)
                --disableNodeJS
                --disableYarnAudit ${{ parameters.excludeArgs }}
                --retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json
                --retireJsForceUpdate
```

```log
Starting Dependency Check...
Setting report directory to D:\a\1\TestResults\dependency-check
Creating report directory at D:\a\1\TestResults\dependency-check
Downloading Dependency Check latest installer from GitHub..
Downloading ZIP from "[https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip"...](https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip%22...)
Dependency Check script set to D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Invoking Dependency Check...
Path: D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Arguments: --project "PulseBolt" --out "D:\a\1\TestResults\dependency-check" --scan "D:\a\1\PulseBoltArtifact\MxProduct" --format HTML --format  JUNIT --failOnCVSS 7 --suppression "D:\a\1\owasp-suppression.xml" --enableExperimental --ossIndexUsername *** --ossIndexPassword *** --disableNodeJS --disableYarnAudit --exclude "**/Qt5*.dll" --exclude "**/signaling-server/*" --exclude "**/Nuvasive*.dll" --exclude "**/vendor*.js"
 --retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json --retireJsForceUpdate
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat --version"
Dependency-Check Core version 8.4.2
...
[ERROR] Failed to initialize the RetireJS repo: `C:\Users\VSSADM~1\AppData\Local\Temp\dctemp864a8f21-557a-4aaa-ad88-37ce0b8f95ec\jsrepository.json` appears to be malformed. Please delete the file or run the dependency-check purge command and re-try running dependency-check.
``` 

Here's the working version

```yaml
          - task: dependency-check-build-task@6
            displayName: OWASP Dependency Check
            inputs:
              projectName: '${{ parameters.release }}'
              scanPath: '$(Pipeline.Workspace)/${{ parameters.release }}Artifact/${{ coalesce(parameters.artifactName, parameters.product, ''drop'') }}'
              format: 'HTML, JUNIT'
              failOnCVSS: '$(failOnCVSS)'
              suppressionPath: '$(Pipeline.Workspace)\owasp-suppression.xml'
              enableExperimental: ${{ parameters.enableExperimental }}
              additionalArguments: >
                --retireJsForceUpdate
                --retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json
                --ossIndexUsername $(ossIndexUsername)
                --ossIndexPassword $(ossIndexPassword)
                --disableNodeJS
                --disableYarnAudit ${{ parameters.excludeArgs }}
```

```log
Starting Dependency Check...
Setting report directory to D:\a\1\TestResults\dependency-check
Creating report directory at D:\a\1\TestResults\dependency-check
Downloading Dependency Check latest installer from GitHub..
Downloading ZIP from "[https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip"...](https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip%22...)
Dependency Check script set to D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Invoking Dependency Check...
Path: D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat
Arguments: --project "PulseBolt" --out "D:\a\1\TestResults\dependency-check" --scan "D:\a\1\PulseBoltArtifact\MxProduct" --format HTML --format  JUNIT --failOnCVSS 7 --suppression "D:\a\1\owasp-suppression.xml" --enableExperimental --retireJsForceUpdate --retireJsUrl https://raw.githubusercontent.com/RetireJS/retire.js/0fe12bb575eda270536dc0ce47fca0dd17b6ab33/repository/jsrepository.json --ossIndexUsername *** --ossIndexPassword *** --disableNodeJS --disableYarnAudit --exclude "**/Qt5*.dll" --exclude "**/signaling-server/*" --exclude "**/Nuvasive*.dll" --exclude "**/vendor*.js"
C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tasks\dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72\6.1.1\dependency-check\bin\dependency-check.bat --version"
Dependency-Check Core version 8.4.2
```

**Expected behavior**
The task honors all arguments regardless of where they are placed.

**Additional context**
N/A
