### ISSUE TITLE
Version 9.0.0 breaks Azure DevOps Extension

### ISSUE THREAD

**Issue by LucaBlackDragon** [dependency-check/DependencyCheck#6103]
**Describe the bug**
Just wanted to let you know that version 9.0.0 of the cli seems to break our CI/CD pipeline on Azure DevOps, configured as such:
```yml
  - task: dependency-check-build-task@6
    displayName: OWASP Dependency Check
    inputs:
      projectName: '$(mainProject)'
      scanPath: '$(Build.ArtifactStagingDirectory)/code'
      format: 'HTML, SARIF'
      suppressionPath: 'owasp-suppressions.xml'
```
And based on the [OWASP Dependency Check Azure DevOps Extension](https://github.com/dependency-check/azuredevops).
This same configuration used to work with cli 8.4.2.

**Version of dependency-check used**
The problem occurs using version 9.0.0 of the cli

**Log file**
https://gist.github.com/LucaBlackDragon/b35d7c418ca72f5dabed145d032fa5a0

**Additional context**
The error message suggests to purge the database, but this is not easily done in a CI/CD pipeline.
Anyway, we can pin the cli version with the `dependencyCheckVersion` option in our pipeline config, so no real issue here, I just wanted to notify you.
