### ISSUE TITLE
"Autoupdate is disabled and the database does not exist" when running DependencyCheck v8.3.1

### ISSUE THREAD

**Issue by sicil1ano** [dependency-check/DependencyCheck#6176]
Hi. I don't understand what this error means.

I'm running DependencyCheck v8.3.1 using this extension: https://github.com/dependency-check/azuredevops in Azure DevOps.
I'm using the "dataMirror" option of the extension, passing the URL of the ZIP archive containing the "data" folder used by DependencyCheck.  
Using this option, the DevOps extension will extract the ZIP archive into the "data" folder of the tool. 
The ZIP archive was generated in a previous run by running DependencyCheck with `--updateonly` option.

I am also using `--noupdate` option because there is no need to download NVE and CVE files since I am already providing them to the tool with the ZIP archive.
I'm running the tool on a clean Ubuntu agent, where I checkout the repository I want to scan.

This is the log of the DevOps extension task running the tool.

Why am I getting this error? What do I need to do to fix it? Is an upgrade to 9.0.1 needed?

```
Starting Dependency Check...
Setting report directory to /home/vsts/work/_temp/dependency-scan-results
Creating report directory at /home/vsts/work/_temp/dependency-scan-results
Downloading Dependency Check 8.3.1 installer from GitHub..
Downloading ZIP from "[https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip"...](https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip%22...)
Downloading Dependency Check data cache archive...
Downloading ZIP from "[https://mycdn.net/owaspcache/latestOwaspFiles.zip"...](https://mycdn.net/owaspcache/latestOwaspFiles.zip%22...)
Dependency Check script set to /home/vsts/work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.1.1/dependency-check/bin/dependency-check.sh
Invoking Dependency Check...
Path: /home/vsts/work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.1.1/dependency-check/bin/dependency-check.sh
Arguments: --project "MyProject" --out "/home/vsts/work/_temp/dependency-scan-results" --scan "/home/vsts/work/1/s/**/*.csproj" --format HTML --format  JSON --format  JUNIT --suppression "/home/vsts/work/1/s/owasp-dependency-check-suppressions.xml" --noupdate
/home/vsts/work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.1.1/dependency-check/bin/dependency-check.sh --version
Dependency-Check Core version 8.3.1

Searching for left over lock files...
found no left over lock files, continuing...
/home/vsts/work/_tasks/dependency-check-build-task_47ea1f4a-57ba-414a-b12e-c44f42765e72/6.1.1/dependency-check/bin/dependency-check.sh --project MyProject --out /home/vsts/work/_temp/dependency-scan-results --scan /home/vsts/work/1/s/**/*.csproj --format HTML --format JSON --format JUNIT --suppression /home/vsts/work/1/s/owasp-dependency-check-suppressions.xml --noupdate
[ERROR] One or more fatal errors occurred
[ERROR] Autoupdate is disabled and the database does not exist

Dependency Check completed with exit code 13.
Dependency Check reports:
[]
Dependency Check failed with message "Dependency Check exited with an error code (exit code: 13)."
##[error]Dependency Check exited with an error code (exit code: 13).
Ending Dependency Check... 
```

You can find my YAML code below. Thanks for help!

```
parameters:
  - name: projects
    displayName: Specifies the projects to scan for dependencies with known vulnerabilities.
    type: string
    default: "$(Build.Repository.LocalPath)/**/*.csproj"

  - name: owaspDependencyCheckVersion
    displayName: Specify version of OWASP Dependency Check to use.
    type: string
    default: 8.3.1

  - name: dataMirror
    displayName: The HTTP/HTTPS mirror containing a ZIP archive with the files to be used by the OWASP Dependency Check.
    type: string

steps:
  - task: dependency-check-build-task@6
    displayName: "Run OWASP Dependency Check Scan"
    inputs:
      projectName: $(Build.Repository.Name)
      scanPath: ${{ parameters.projects }}
      format: "HTML, JSON, JUNIT"
      reportsDirectory: "$(Agent.TempDirectory)/dependency-scan-results"
      dependencyCheckVersion: ${{ parameters.owaspDependencyCheckVersion }}
      suppressionPath: "$(System.DefaultWorkingDirectory)/owasp-dependency-check-suppressions.xml"
      dataMirror: ${{ parameters.dataMirror }}
      additionalArguments: "--noupdate"
```
