### ISSUE TITLE
Significant Increase in CI Workflow Duration After Dependency-Check Upgrade

### ISSUE THREAD

**Issue by atilsensalduz** [dependency-check/DependencyCheck#6226]
Following the upgrade of the dependency-check tool from version 8.4.3 to 9.0.2, we have noticed a considerable increase in our CI workflow duration. The workflow, which runs on GitHub Actions, now takes approximately 50 minutes to complete.

To perform the dependency-check, we are using the following command in our Maven build:

`mvn --no-transfer-progress clean package -DskipTests -DskipITs -Dmax.cvss.score=8 org.owasp:dependency-check-maven:check -l ${{github.workspace}}/mvn-output.txt`

We need assistance in understanding whether this is a bug introduced with the newer version or if there's something we might have overlooked in our codebase. Thanks in advance

**Comment by TobiX** [comment]
Are you using an NVD API key and/or caching the database, as described [in the documentation](https://github.com/jeremylong/DependencyCheck#900-upgrade-notice)? Otherwise, this is expected, since the NVD API is heavily rate-limited.

**Comment by jeremylong** [comment]
It is not a bug - rather a not well documented implementation procedure. We are working on the documentation (see https://github.com/jeremylong/DependencyCheck/pull/6220). 

Even prior to 9.x it would have been advisable to keep a copy of the data directory between executions. With 9.x it is almost necessary.

**Comment by jeremylong** [comment]
This change was not because we wanted to change - but more that the original data source at the NVD is being deprecated and replaced with an API that is not as fast.

**Comment by jeremylong** [comment]
oh - and yes, the API key is really important as well. Thanks @TobiX

**Comment by atilsensalduz** [comment]
Thanks for the prompt response, guys. I've requested the `nvdApiKey`. Can you confirm if the following workflow is correct? Additionally, do you have any guidance on how I should configure the cache for it? Would `cache: 'maven'` in the `Set up JDK 17` step be sufficient?

```
name: Vulnerability Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  owasp-scan:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: 'maven'

      - name: Build & scan
        id: scan
        run: |
          mvn --no-transfer-progress clean package -DskipTests -DnvdApiKey=${{secret.nvdApiKey}} -DskipITs -Dmax.cvss.score=8 \
            org.owasp:dependency-check-maven:check -l ${{github.workspace}}/mvn-output.txt 
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME}}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD}}
```

**Comment by jeremylong** [comment]
I would highly recommend using the `actions/cache@v3` action to cache the data directory. Possibly something like:

```
 - name: Cache ODC Data
        id: odc-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data/
          key: odc-cache
          restore-keys: |
            odc-cache
```

Note that the above has not been tested yet.

**Comment by atilsensalduz** [comment]
Thanks a ton for your help on the issue! Your guidance was awesome, and I really appreciate it. You rock!

**Comment by jeremylong** [comment]
@atilsensalduz did you use the `actions/cache@v3` - is what I wrote working?

**Comment by atilsensalduz** [comment]
Hey @jeremylong, apologies for the delay. I gave your suggestion a shot, but the workflow still took around 20 minutes. I tweaked the cache settings as follows, and now it's down to 2 minutes

```
name: Vulnerability Scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  owasp-scan:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: 'maven'
          
      - name: Get Date
        id: get-date
        run: |
          echo "datetime=$(/bin/date -u "+%Y%m%d%H")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore cached Maven dependencies
        uses: actions/cache/restore@v3
        with:
          path: ~/.m2/repository
          # Using datetime in cache key as OWASP database may change, without the pom changing
          key: ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}
            ${{ runner.os }}-maven-
            
      - name: Build & scan
        id: scan
        run: |
          mvn --no-transfer-progress clean package -DskipTests -DnvdApiKey=${{secrets.nvdApiKey}} -DskipITs -Dmax.cvss.score=8 \
            org.owasp:dependency-check-maven:check -l ${{github.workspace}}/mvn-output.txt 
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME}}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD}}
          
     - name: Cache Maven dependencies
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ steps.get-date.outputs.datetime }}-${{ hashFiles('**/pom.xml') }}

```
