### ISSUE TITLE
Dependency-Check Action not Executed in Java Maven Project

### ISSUE THREAD

**Issue by T-baby** [dependency-check/DependencyCheck#6902]
My project is a Java Maven project with dependency-check/Dependency-Check_Action configured in GitHub Actions, but the scan is not actually being scanned.

```
      - name: Maven Install
        run: mvn -B install -DskipTests

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # actions/setup-java@ changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        with:
          project: ${{ steps.meta.outputs.REPO_NAME }}
          path: '.'
          format: 'JSON'
          out: 'reports'
          args: >
            --enableRetired
```

![image](https://github.com/user-attachments/assets/33c66b23-f21b-42ee-9d88-4b9107b38b3f)
