### ISSUE TITLE
not clear how to prepare .NET solution before running dependency check from azure devops pipelines

### ISSUE THREAD

**Issue by pdCGKa** [dependency-check/DependencyCheck#7615]
Hi there,

I'm having a hard time getting the exact correct setup for my .NET 8 C# projects. 

Context:
- Azure DevOps pipelines with yaml
- .NET 8 projects, using Nuget Packages

Some findings:

- When running a nuget restore, and then running a dependency check, I seem to not get all inner dependencies added to the report. Anything that I could to to influence this result without building? I'm not sure what is actually being looked at to get to this result, so I'm not sure how to have influence on it. 
- When I run a build after a restore, this seems to add library.dll instead of library.v1.0.0 to the report, which does not seem to include the correct details about the version. 
- is there any documentation about using yaml tasks? I can't seem to find this
- Are there some examples and explained scenarios documented for this stack? If it exists I seem to look over this.

``` yaml

- task: UseDotNet@2
  displayName: 'Install .NET 8.x SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    performMultiLevelLookup: true

- task: JavaToolInstaller@0
  displayName: 'Use Java 11'
  inputs:
    versionSpec: 11
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled

- task: NugetCommand@2
  displayName: Restore NuGet Packages
  inputs:
    command: restore
    disableParallelProcessing: true
    restoreSolution: '$(system.defaultworkingdirectory)/Common/Common.sln'
    selectOrConfig: config
    nugetConfigPath: '$(system.defaultworkingdirectory)/Common/.nuget/NuGet.config'   

# - task: DotNetCoreCLI@2 # seems to have the effect of adding "libraryname.dll" instead of libraryname.v1.0.0, this seems to be incorrect
#   displayName: Build
#   inputs:
#     command: build
#     projects: '$(system.defaultworkingdirectory)/Common/Common.sln'

- download: 'Cache vulnerability database'
  artifact: NVDDB
  displayName: Download OWASP Dependency Check Data

- task: dependency-check.dependencycheck.dependency-check-build-task.dependency-check-build-task@6
  displayName: 'Dependency Check'
  inputs:
    projectName: projectname
    scanPath:  projectpath/**
    format: 'HTML,JSON'
    warnOnCVSSViolation: true
    additionalArguments: '--disableYarnAudit --data "$(Pipeline.Workspace)/Cache vulnerability database/NVDDB" --noupdate'
    dependencyCheckVersion: 'latest'

```
